apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/ketchupCoding43/argocd-repo.git'
    targetRevision: HEAD
    path: apps/headlamp/base
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: headlamp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

