apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ketchupCoding43/argocd-repo.git
    targetRevision: HEAD
    path: apps/headlamp/base
    helm:
      values: |
        replicaCount: 1
        service:
          type: NodePort
          port: 80
        nodePort: 30080
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
