apiVersion: apps/v1
kind: Deployment
metadata:
  name: k9s-dashboard
spec:
  template:
    spec:
      containers:
        - name: k9s-web
          image: ghcr.io/someuser/k9s-web-wrapper:latest  # Replace with real gotty-wrapped k9s image
