apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  namespace: default
  labels:
    app: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp-admin  # <== Add this line!
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.21.0
          ports:
            - name: http
              containerPort: 8080
          env:
            #- name: HEADLAMP_ALLOWED_KUBECONFIGS
            #  value: ""
            - name: HEADLAMP_MODE
              value: "frontend"  # 👈 Forces login mode
            - name: HEADLAMP_TOKEN_LOGIN
              value: "true"
            - name: HEADLAMP_DISABLE_CLUSTER_ACCESS
              value: "true"
