apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
  labels:
    app: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: headlamp
  template:
    metadata:
      labels:
        app: headlamp
    spec:
      serviceAccountName: headlamp-admin  # Make sure your ServiceAccount is bound!
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.21.0
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: HEADLAMP_ALLOWED_KUBECONFIGS
              value: ""
            - name: HEADLAMP_TOKEN_LOGIN
              value: "true"
            - name: HEADLAMP_K8S_CLUSTER_URL
              value: "https://kubernetes.default.svc"  # 👈 This tells Headlamp which cluster to show
