apiVersion: v1
kind: Service
metadata:
  name: headlamp
  labels:
    app: headlamp
spec:
  ports:
    - port: 8080
      targetPort: 4466
      protocol: TCP
      name: http
  selector:
    app: headlamp
