apiVersion: v1
kind: Service
metadata:
  name: headlamp
  namespace: headlamp
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 32000  # Adjust nodePort if needed
  selector:
    app: headlamp
