apiVersion: v1
kind: Service
metadata:
  name: headlamp
spec:
  type: NodePort
  selector:
    app: headlamp
  ports:
    - port: 80
      targetPort: 4466
      nodePort: 32000  # NordPort or external tool will use this port
