apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k9s-admin
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups: ["apps", "extensions"]
    resources: ["*"]
    verbs: ["*"]
