apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k9s-admin-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k9s-admin
subjects:
  - kind: ServiceAccount
    name: k9s-admin
    namespace: k9s-dev  # will be overridden by overlays
