apiVersion: v1
kind: Service
metadata:
  name: k9s-dashboard
spec:
  type: NodePort
  selector:
    app: k9s-dashboard
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30090  # Exposed NodePort (adjust if needed)
