apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/argocd-repo
    targetRevision: HEAD
    path: apps/headlamp/base
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: headlamp
  syncPolicy:
    automated:  # this enables auto-sync
      prune: true
      selfHeal: true
