apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: headlamp
  namespace: argocd
spec:
  project: test-project
  source:
    repoURL: https://github.com/ketchupCoding43/argocd-repo.git
    targetRevision: main
    path: apps/headlamp/base
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

