apiVersion: apps/v1
kind: Deployment
metadata:
  name: headlamp
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:v0.4.0  # Pin specific version
