apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: headlamp

bases:
  - ../../base

patchesStrategicMerge:
  - deployment.yaml  # Optional: patch replicas, image tags, etc.
  - namespace.yaml
  - service.yaml
